name: Dev CI

on:
  push:
    tags:
      - 'v*'
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        name: run unit test
        run: ./gradlew test


  build:
    runs-on: ubuntu-latest
    steps:
      #1
      - uses: actions/checkout@v3

      #2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      #3
      - name: Generate APK
        run: ./gradlew assembleDevRelease

      #4
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/dev/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      #5 upload signed apk
      - uses: actions/upload-artifact@master
        with:
            name: app-dev-release.apk
            path: ${{steps.sign_app.outputs.signedReleaseFile}}

      #6
      - uses: actions/upload-artifact@master
        with:
            name: mapping.txt
            path: app/build/outputs/mapping/devRelease/mapping.txt

      #7
  deploy-firebase-distribution:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: app-dev-release.apk

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: dev-tester
          file: app-dev-release-signed.apk







